# Generated by Django 2.2.12 on 2022-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220422_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ManyToManyField(help_text='Seleccione un lenguaje para este libro', to='catalog.Language'),
        ),
    ]
